# Generated by Django 3.0.2 on 2020-01-14 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('approve_status', models.BooleanField(default=False)),
                ('loan_request_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
